export interface DemoPropertyDefinition {
  apn: string;
  address_line1: string;
  city: string;
  state: string;
  zip: string;
  county: string;
  property_type: string;
  bedrooms: number;
  bathrooms: number;
  square_feet: number;
  lot_size_sqft: number;
  year_built: number;
  estimated_value: number;
  estimated_equity: number;
  equity_percent: number;
  estimated_rent: number;
  last_sale_price: number;
  mortgage_balance: number;
  tax_delinquent: number;
  is_vacant: number;
  is_absentee_owner: number;
  is_pre_foreclosure: number;
  is_probate: number;
  has_liens: number;
  owner_name: string;
  revzenta_opportunity_score: number;
  opportunity_score_reasons: string;
  source_provider: string;
}

export const NATIONWIDE_DEMO_PROPERTIES: DemoPropertyDefinition[] = [
  // Phoenix / Maricopa County, AZ
  {
    apn: "114-22-045A",
    address_line1: "4521 E Indian School Rd",
    city: "Phoenix",
    state: "AZ",
    zip: "85018",
    county: "maricopa",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1720,
    lot_size_sqft: 7500,
    year_built: 1982,
    estimated_value: 385000,
    estimated_equity: 211750,
    equity_percent: 55,
    estimated_rent: 2450,
    last_sale_price: 180000,
    mortgage_balance: 173250,
    tax_delinquent: 0,
    is_vacant: 1,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Marcus Vance (Absentee)",
    revzenta_opportunity_score: 92,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "Vacant Property", "55% Equity Cushion", "High Rental Demand"]),
    source_provider: "RentCast",
  },
  {
    apn: "156-89-102C",
    address_line1: "1428 W Campbell Ave",
    city: "Phoenix",
    state: "AZ",
    zip: "85015",
    county: "maricopa",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1540,
    lot_size_sqft: 6800,
    year_built: 1976,
    estimated_value: 340000,
    estimated_equity: 190400,
    equity_percent: 56,
    estimated_rent: 2200,
    last_sale_price: 155000,
    mortgage_balance: 149600,
    tax_delinquent: 1,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Elena Rostova",
    revzenta_opportunity_score: 89,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "Tax Delinquent", "High Equity Cushion", "Wholesale Discount"]),
    source_provider: "RentCast",
  },
  {
    apn: "173-04-512",
    address_line1: "7822 E McDowell Rd",
    city: "Scottsdale",
    state: "AZ",
    zip: "85257",
    county: "maricopa",
    property_type: "Single Family",
    bedrooms: 4,
    bathrooms: 2.5,
    square_feet: 2180,
    lot_size_sqft: 8900,
    year_built: 1988,
    estimated_value: 520000,
    estimated_equity: 312000,
    equity_percent: 60,
    estimated_rent: 3200,
    last_sale_price: 240000,
    mortgage_balance: 208000,
    tax_delinquent: 0,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Desert Sun Holdings LLC",
    revzenta_opportunity_score: 87,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "60% Equity Spread", "Scottsdale Appreciation Corridor"]),
    source_provider: "Attom",
  },
  {
    apn: "138-12-880",
    address_line1: "2109 S Elm St",
    city: "Mesa",
    state: "AZ",
    zip: "85204",
    county: "maricopa",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1610,
    lot_size_sqft: 7100,
    year_built: 1984,
    estimated_value: 315000,
    estimated_equity: 176400,
    equity_percent: 56,
    estimated_rent: 2100,
    last_sale_price: 140000,
    mortgage_balance: 138600,
    tax_delinquent: 0,
    is_vacant: 1,
    is_absentee_owner: 0,
    is_pre_foreclosure: 1,
    is_probate: 0,
    has_liens: 1,
    owner_name: "Kenneth Baker",
    revzenta_opportunity_score: 94,
    opportunity_score_reasons: JSON.stringify(["Pre-Foreclosure Filing", "Vacant Property", "Title Lien Recorded", "Deep Equity"]),
    source_provider: "RentCast",
  },
  {
    apn: "111-45-620",
    address_line1: "834 N 5th Ave",
    city: "Phoenix",
    state: "AZ",
    zip: "85003",
    county: "maricopa",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1820,
    lot_size_sqft: 6500,
    year_built: 1965,
    estimated_value: 460000,
    estimated_equity: 239200,
    equity_percent: 52,
    estimated_rent: 2700,
    last_sale_price: 210000,
    mortgage_balance: 220800,
    tax_delinquent: 0,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 1,
    owner_name: "Arthur Pendelton",
    revzenta_opportunity_score: 85,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "Downtown Phoenix Infill", "SubTo Viability"]),
    source_provider: "Attom",
  },

  // Florida Markets (Miami, Tampa, Orlando, Hollywood)
  {
    apn: "01-3114-023-1190",
    address_line1: "2841 NW 17th St",
    city: "Miami",
    state: "FL",
    zip: "33125",
    county: "miami-dade",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1480,
    lot_size_sqft: 5500,
    year_built: 1968,
    estimated_value: 245000,
    estimated_equity: 164150,
    equity_percent: 67,
    estimated_rent: 2300,
    last_sale_price: 98000,
    mortgage_balance: 80850,
    tax_delinquent: 1,
    is_vacant: 1,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Rodriguez Family Trust",
    revzenta_opportunity_score: 96,
    opportunity_score_reasons: JSON.stringify(["Vacant Property", "Delinquent Property Taxes", "67% Equity Cushion", "Cash Wholesale Target"]),
    source_provider: "RentCast",
  },
  {
    apn: "19-29-19-4U2-000010",
    address_line1: "4912 E 10th Ave",
    city: "Tampa",
    state: "FL",
    zip: "33605",
    county: "hillsborough",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 1.5,
    square_feet: 1350,
    lot_size_sqft: 6200,
    year_built: 1974,
    estimated_value: 220000,
    estimated_equity: 149600,
    equity_percent: 68,
    estimated_rent: 1950,
    last_sale_price: 85000,
    mortgage_balance: 70400,
    tax_delinquent: 1,
    is_vacant: 1,
    is_absentee_owner: 0,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Clara Higgins",
    revzenta_opportunity_score: 93,
    opportunity_score_reasons: JSON.stringify(["Vacant", "Back Taxes Owed", "Tampa Urban Core", "High Margin Assignment"]),
    source_provider: "RentCast",
  },
  {
    apn: "29-22-29-5840-02-180",
    address_line1: "1304 W Gore St",
    city: "Orlando",
    state: "FL",
    zip: "32805",
    county: "orange",
    property_type: "Single Family",
    bedrooms: 2,
    bathrooms: 1,
    square_feet: 1120,
    lot_size_sqft: 6000,
    year_built: 1962,
    estimated_value: 195000,
    estimated_equity: 140400,
    equity_percent: 72,
    estimated_rent: 1750,
    last_sale_price: 65000,
    mortgage_balance: 54600,
    tax_delinquent: 0,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 1,
    has_liens: 0,
    owner_name: "Estate of Donald Vance",
    revzenta_opportunity_score: 91,
    opportunity_score_reasons: JSON.stringify(["Probate / Inherited Property", "Absentee Heir", "72% Equity", "Motivated Seller"]),
    source_provider: "Attom",
  },
  {
    apn: "5142-14-04-0320",
    address_line1: "3219 N 29th Ave",
    city: "Hollywood",
    state: "FL",
    zip: "33020",
    county: "broward",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1600,
    lot_size_sqft: 5800,
    year_built: 1980,
    estimated_value: 248000,
    estimated_equity: 133920,
    equity_percent: 54,
    estimated_rent: 2400,
    last_sale_price: 120000,
    mortgage_balance: 114080,
    tax_delinquent: 1,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Sunrise Properties LLC",
    revzenta_opportunity_score: 88,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "Tax Delinquent", "South Florida Cash Flow"]),
    source_provider: "RentCast",
  },

  // Dallas & Fort Worth, Texas
  {
    apn: "00000459201000000",
    address_line1: "3518 Metropolitan Ave",
    city: "Dallas",
    state: "TX",
    zip: "75210",
    county: "dallas",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1560,
    lot_size_sqft: 6500,
    year_built: 1978,
    estimated_value: 215000,
    estimated_equity: 159100,
    equity_percent: 74,
    estimated_rent: 1900,
    last_sale_price: 75000,
    mortgage_balance: 55900,
    tax_delinquent: 0,
    is_vacant: 0,
    is_absentee_owner: 0,
    is_pre_foreclosure: 1,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Darren Jefferson",
    revzenta_opportunity_score: 95,
    opportunity_score_reasons: JSON.stringify(["Pre-Foreclosure Notice Recorded", "74% Equity Cushion", "Single Family", "Urgent Seller Timeline"]),
    source_provider: "RentCast",
  },
  {
    apn: "00000678102000000",
    address_line1: "2407 Elsie Ave",
    city: "Dallas",
    state: "TX",
    zip: "75216",
    county: "dallas",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1420,
    lot_size_sqft: 6200,
    year_built: 1981,
    estimated_value: 230000,
    estimated_equity: 154100,
    equity_percent: 67,
    estimated_rent: 1950,
    last_sale_price: 90000,
    mortgage_balance: 75900,
    tax_delinquent: 0,
    is_vacant: 1,
    is_absentee_owner: 1,
    is_pre_foreclosure: 1,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Oak Cliff Assets Co",
    revzenta_opportunity_score: 92,
    opportunity_score_reasons: JSON.stringify(["Pre-Foreclosure", "Vacant", "Absentee Owner", "High Investor Demand"]),
    source_provider: "Attom",
  },
  {
    apn: "04291823",
    address_line1: "1805 Gould Ave",
    city: "Fort Worth",
    state: "TX",
    zip: "76164",
    county: "tarrant",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 1,
    square_feet: 1280,
    lot_size_sqft: 5800,
    year_built: 1960,
    estimated_value: 185000,
    estimated_equity: 129500,
    equity_percent: 70,
    estimated_rent: 1650,
    last_sale_price: 60000,
    mortgage_balance: 55500,
    tax_delinquent: 1,
    is_vacant: 1,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Guadalupe Morales",
    revzenta_opportunity_score: 90,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "Vacant", "Tax Delinquent", "High Equity Spread"]),
    source_provider: "RentCast",
  },

  // Atlanta, GA
  {
    apn: "14-0182-0004-051-2",
    address_line1: "1124 Hollywood Rd NW",
    city: "Atlanta",
    state: "GA",
    zip: "30318",
    county: "fulton",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1620,
    lot_size_sqft: 7200,
    year_built: 1972,
    estimated_value: 225000,
    estimated_equity: 159750,
    equity_percent: 71,
    estimated_rent: 1850,
    last_sale_price: 78000,
    mortgage_balance: 65250,
    tax_delinquent: 1,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 0,
    has_liens: 1,
    owner_name: "Apex Global Investments",
    revzenta_opportunity_score: 93,
    opportunity_score_reasons: JSON.stringify(["Absentee Owner", "Tax Delinquent", "Recorded Liens", "71% Equity Spread"]),
    source_provider: "RentCast",
  },
  {
    apn: "14-0118-0008-012-9",
    address_line1: "876 Sells Ave SW",
    city: "Atlanta",
    state: "GA",
    zip: "30310",
    county: "fulton",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1750,
    lot_size_sqft: 6800,
    year_built: 1968,
    estimated_value: 260000,
    estimated_equity: 179400,
    equity_percent: 69,
    estimated_rent: 2100,
    last_sale_price: 95000,
    mortgage_balance: 80600,
    tax_delinquent: 0,
    is_vacant: 1,
    is_absentee_owner: 1,
    is_pre_foreclosure: 0,
    is_probate: 1,
    has_liens: 0,
    owner_name: "Estate of Walter Sterling",
    revzenta_opportunity_score: 91,
    opportunity_score_reasons: JSON.stringify(["Probate Property", "Vacant", "West End Atlanta Appreciation", "Motivated Heirs"]),
    source_provider: "Attom",
  },

  // North Las Vegas, NV
  {
    apn: "139-21-310-045",
    address_line1: "2201 Hassell Ave",
    city: "North Las Vegas",
    state: "NV",
    zip: "89032",
    county: "clark",
    property_type: "Single Family",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1580,
    lot_size_sqft: 6000,
    year_built: 1996,
    estimated_value: 295000,
    estimated_equity: 171100,
    equity_percent: 58,
    estimated_rent: 2150,
    last_sale_price: 135000,
    mortgage_balance: 123900,
    tax_delinquent: 0,
    is_vacant: 0,
    is_absentee_owner: 1,
    is_pre_foreclosure: 1,
    is_probate: 0,
    has_liens: 0,
    owner_name: "Silver State Holdings",
    revzenta_opportunity_score: 89,
    opportunity_score_reasons: JSON.stringify(["Pre-Foreclosure", "Absentee Owner", "High Rental Yield"]),
    source_provider: "RentCast",
  },
];
